version: "3.7"
services:
  eatspam:
    image: darthbermel/eatspam:latest
    container_name: eatspam
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./config:/app/config
    environment:
      - CONTAINER_NAME=eatspam
