name: Docker Image CI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2
      name: Setup buildx
      id:  buildx
      with:
        install: true

    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Login to Docker Hub
      run: |

    - name: Build and push images
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag darthbermel/eatspam:test .